# Basic commands

In [ ]:
import torch

In [2]:
# create an empty tensor (prints a a 2x3 matrix)
x = torch.empty(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [3]:
# we can also represent the tensor as zeros
x = torch.zeros(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
# or ones
x = torch.ones(2,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [7]:
# we can also specify the data type within the tensor
x = torch.ones(2,3, dtype=torch.int)
print(x.dtype)

torch.int32


In [8]:
# we can also look at the size of the tensor
x = torch.ones(2,3, dtype=torch.int)
print(x.size())

torch.Size([2, 3])


In [9]:
# creating a tensor from a python list
x = torch.tensor([3.4, 1.3, 5.3])
print(x)

tensor([3.4000, 1.3000, 5.3000])


In [11]:
# perform simple calculations on two tensors - like addition
x = torch.rand(2,3)
y = torch.rand(2,3)

# use 'add' to add them together
z = torch.add(x,y)
print(z)

tensor([[1.1871, 1.0251, 1.1229],
        [1.0490, 0.4154, 1.4108]])


In [12]:
# alternative approach to addition - add in place
# note: inclusion of a trailing underscore indicates that the function is an in place operation
x = torch.rand(2,3)
y = torch.rand(2,3)

# add values of x to y
y.add_(x)
print(y)

tensor([[1.5824, 0.9468, 0.9668],
        [0.8429, 1.4896, 1.1317]])


In [13]:
# other basic calculations
x = torch.rand(2,3)
y = torch.rand(2,3)

# substitution
z = torch.sub(x,y)
print("Substitute y from x")
print(z)

# multiply
z = torch.mul(x,y)
print("Multiply x and y")
print(z)

# divide
z = torch.div(x,y)
print("Divide y from x")
print(z)


Substitute y from x
tensor([[-0.0315, -0.0095,  0.0738],
        [ 0.1580, -0.4180, -0.0996]])
Multiply x and y
tensor([[0.3324, 0.6446, 0.0011],
        [0.0323, 0.1581, 0.6882]])
Divide y from x
tensor([[0.9468, 0.9882, 6.8299],
        [2.3464, 0.3649, 0.8869]])


In [15]:
# we can also slice into a tensor and access a single row or column
x = torch.rand(2,5)
print(x)

# get all rows but only for the first column
print(x[:,0])

tensor([[0.9446, 0.5592, 0.1314, 0.4660, 0.4892],
        [0.4322, 0.4458, 0.3575, 0.3165, 0.2572]])
tensor([0.9446, 0.4322])


In [16]:
# we can also get the a single row but all columns
print(x[0,:])

tensor([0.9446, 0.5592, 0.1314, 0.4660, 0.4892])


In [18]:
# reshaping a tensor
x = torch.rand(4,4)
print("4x4 tensor")
print(x)

# reshaping a tensor is done with the 'view' function 
# here, we return the original x tensor as in a single dimension
y = x.view(16) # 16 as the total elements in a 4x4 matrix is 16
print(y)

4x4 tensor
tensor([[0.5994, 0.6195, 0.4770, 0.2178],
        [0.1295, 0.9117, 0.5175, 0.1416],
        [0.1615, 0.4728, 0.7006, 0.0973],
        [0.5461, 0.5097, 0.6459, 0.5636]])
tensor([0.5994, 0.6195, 0.4770, 0.2178, 0.1295, 0.9117, 0.5175, 0.1416, 0.1615,
        0.4728, 0.7006, 0.0973, 0.5461, 0.5097, 0.6459, 0.5636])


In [20]:
# alternatively, setting the first parameter to -1 means we can specify the number of elements we want 
y = x.view(-1, 8)
print(y)

tensor([[0.5994, 0.6195, 0.4770, 0.2178, 0.1295, 0.9117, 0.5175, 0.1416],
        [0.1615, 0.4728, 0.7006, 0.0973, 0.5461, 0.5097, 0.6459, 0.5636]])


In [21]:
# converting between numpy and torch
import numpy as np

# create a tensor of ones
a = torch.ones(5)
print("Pytorch tensor")
print(a)
print(a.dtype)

# convert to numpy
b = a.numpy()
print("Numpy array")
print(b)
print(b.dtype)

Pytorch tensor
tensor([1., 1., 1., 1., 1.])
torch.float32
Numpy array
[1. 1. 1. 1. 1.]
float32


In [23]:
# you can also convert numpy to tensor
a = np.ones(5)
print(f"Numpy data type: {a.dtype}")

b = torch.from_numpy(a)
print(f"Tensor data type: {b.dtype}")

float64


### Note on converting between tensors and numpy arrays
When converting between pytorch tensors and numpy arrays, it is important to note that whe using a CPU they are stored in the same location in memory. This means that changes to one will automatically be reflected in the other.

In [24]:
# for instance, add 1 to a, and its changes will be reflected in b
a +=1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [25]:
# if working with CUDA, one solution is to add the tensor to the GPU
# note: this is for illustrative purposes as I don't have a GPU to run this on.
if torch.cuda.is_available():
    # specify location of GPU
    device = torch.device("cuda")
    # add tensor directly on to GPU
    x = torch.ones(5, device=device)
    # alternatively, we create the tensor on the CPU and then add it to GPU later
    y = torch.ones(5)
    y.to(device)
    # we can then perform the same calculations on the GPU before moving it back to CPU with similar terminology
    z = torch.add(x,y)
    # move z back to CPU
    z.to("cpu")
else:
    print("GPU not available")

GPU not available


In [ ]:
# include 'requires_grad=True' if you need to calculate gradients later in the pipeline
x = torch.ones(5, requires_grad=True)